# ML Assignment 02
### Dataset: House Price Prediction Dataset
### Total Marks: 100

---

## Exam Instructions:
1. প্রথমে নিচের cell এ নিজের **নাম** এবং কোর্সে registration করা **ইমেইল** দিবে
2. Question wise numbering করে Text cell রাখবে এবং এর নিচে Code cell থাকবে, চেষ্টা করবে একটি code cell এ একটি question উত্তর দেওয়ার
3. Google Colab এর মধ্যে কোডগুলো করবে
4. এবং সেই ফাইলটি **'Anyone with the link' & 'View' Access** দিয়ে ফাইলটির Shareable Link টি সাবমিট করবে

---

**Question Dataset Link:** https://www.kaggle.com/datasets/prokshitha/home-value-insights

## Student Information

In [ ]:
# Fill in your information
name = "Sadman wahid"           # Write your full name here
email = "sadmanwahid307@gmail.com"          # Write your registered email here

print(f"Name  : {name}")
print(f"Email : {email}")

Name  : Sadman wahid
Email : sadmanwahid307@gmail.com

---
## Question 1 (10 Marks)

Load the House Price dataset and display:
- Dataset shape
- First 10 rows
- 5 random samples

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "house_price_regression_dataset.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "prokshitha/home-value-insights",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

/tmp/ipykernel_611/914793632.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'home-value-insights' dataset.

In [ ]:
df.shape

(1000, 8)

In [ ]:
# Question 1
print(df.head(10))
print(df.sample(5))

   Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  \
0            1360             2              1        1981  0.599637
1            4272             3              3        2016  4.753014
2            3592             1              2        2016  3.634823
3             966             1              2        1977  2.730667
4            4926             2              1        1993  4.699073
5            3944             5              3        1990  2.475930
6            3671             1              2        2012  4.911960
7            3419             1              1        1972  2.805281
8             630             3              3        1997  1.014286
9            2185             4              2        1981  3.941604

   Garage_Size  Neighborhood_Quality   House_Price
0            0                     5  2.623829e+05
1            1                     6  9.852609e+05
2            0                     9  7.779774e+05
3            1                     8  2.296989e+05
4            0                     8  1.041741e+06
5            2                     8  8.797970e+05
6            0                     1  8.144279e+05
7            1                     1  7.034131e+05
8            1                     8  1.738750e+05
9            2                     5  5.041765e+05
     Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  \
796            2363             1              3        2008  3.284474
774            2408             2              2        1975  1.134984
521            4012             3              1        2016  2.098092
764            3458             5              2        1998  1.609340
663            3266             5              2        1983  3.707807

     Garage_Size  Neighborhood_Quality    House_Price
796            0                     6  528869.862549
774            0                     8  476966.936268
521            1                     5  901000.488234
764            1                     3  760720.146464
663            2                     7  738226.711972

---
## Question 2 (10 Marks)

Handle missing values and perform feature engineering:
- Impute missing numerical values using `SimpleImputer` with mean strategy
- Impute missing categorical values using most frequent strategy
- Drop columns with more than 50% missing values
- Perform train-test split with `test_size=0.2` and `random_state=42`

Display the shape of final train and test sets.

In [ ]:
#Question 2
df.isnull().sum()

Square_Footage          0
Num_Bedrooms            0
Num_Bathrooms           0
Year_Built              0
Lot_Size                0
Garage_Size             0
Neighborhood_Quality    0
House_Price             0
dtype: int64

In [ ]:
# droping columns less than 50%

miss_per = df.isnull().sum() / len(df)
col_drop = miss_per[miss_per > 0.5].index.tolist()
miss_per = df.isnull().sum() / len(df)

col_drop = miss_per[miss_per > 0.5].index.tolist()

if col_drop:
    df = df.drop(columns=col_drop)
    print(f"More than 50% {col_drop}")
else:
    print("Less than 50 % ,There is no need to drop")

Less than 50 % ,There is no need to drop

***Though there is no null value ,yet  we are applying the imputation according to the question.***

In [ ]:
df.columns

Index(['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built',
       'Lot_Size', 'Garage_Size', 'Neighborhood_Quality', 'House_Price'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Square_Footage        1000 non-null   int64
 1   Num_Bedrooms          1000 non-null   int64
 2   Num_Bathrooms         1000 non-null   int64
 3   Year_Built            1000 non-null   int64
 4   Lot_Size              1000 non-null   float64
 5   Garage_Size           1000 non-null   int64
 6   Neighborhood_Quality  1000 non-null   int64
 7   House_Price           1000 non-null   float64
dtypes: float64(2), int64(6)
memory usage: 62.6 KB

In [ ]:
df.head(3)

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,262382.852274
1,4272,3,3,2016,4.753014,1,6,985260.854490
2,3592,1,2,2016,3.634823,0,9,777977.390119

In [ ]:
#imputation
from sklearn.impute import SimpleImputer
import numpy as np

num_features = ['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built', 'Lot_Size', 'Garage_Size']
cate_features = ['Neighborhood_Quality']

# numerical imputation
num_imputer = SimpleImputer(strategy='mean')
df[num_features] = num_imputer.fit_transform(df[num_features])

# categorical imputation
cate_imputer = SimpleImputer(strategy='most_frequent')
df[cate_features] = cate_imputer.fit_transform(df[cate_features])

In [ ]:
#train test split
from sklearn.model_selection import train_test_split

X = df.drop('House_Price', axis=1)
y = df['House_Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (80, 7)
X_test shape: (20, 7)
y_train shape: (80,)
y_test shape: (20,)

---
## Question 3 (20 Marks)

Implement **Simple Linear Regression** using **only NumPy** (no Scikit-Learn allowed):
- Compute slope (`m`) and intercept (`c`) using the Batch Gradient Descent
- Predict values for the test set
- Print the learned `m` and `c` values

Use `Square_Footage` as feature (X) and `House_Price` as target (y).

In [ ]:
#Question 3

# split train test
X_train_arr = np.array(X_train['Square_Footage']).flatten()
y_train_arr = np.array(y_train).flatten()

X_test_arr = np.array(X_test['Square_Footage']).flatten()
y_test_arr = np.array(y_test).flatten()

"""
# y = wx + b
# gradient ::-->
                # w = w - alpha * dj_dw
                # b = b - alpha * dj_db

# dj_dw = (1/m) * np.sum((predictions - y) * X)


# dj_db = (1/m) * np.sum(predictions - y)

"""
w = 0.0
b = 0.0
alpha = 1e-9
iterations = 10000
n = len(X_train_arr)

for i in range(iterations):
    y_pred_train = w * X_train_arr + b

    dw = (1/n) * np.sum((y_pred_train - y_train_arr) * X_train_arr)
    db = (1/n) * np.sum(y_pred_train - y_train_arr)

    w = w - alpha * dw
    b = b - alpha * db

print(f"learned slope (m): {w:.6f}")
print(f"learned intercept (c): {b:.6f}")

y_pred_test = w * X_test_arr + b

print()
for i in range(10):
    print(f"Predicted: {y_pred_test[i]:,.2f}, Actual: {y_test_arr[i]:,.2f}")

learned slope (m): 217.699594
learned intercept (c): 0.169887

Predicted: 182,214.73, Actual: 191,117.10
Predicted: 701,863.66, Actual: 705,754.43
Predicted: 474,149.89, Actual: 480,961.44
Predicted: 949,823.50, Actual: 1,008,539.16
Predicted: 1,087,409.64, Actual: 1,092,026.90
Predicted: 143,899.60, Actual: 147,601.55
Predicted: 721,892.02, Actual: 676,108.85
Predicted: 560,576.63, Actual: 545,482.74
Predicted: 785,895.71, Actual: 774,150.05
Predicted: 873,410.94, Actual: 901,000.49

---
## Question 4 (10 Marks)

Build a **ColumnTransformer** that applies:
- `StandardScaler` on numerical columns: `Square_Footage`, `Num_Bedrooms`, `Num_Bathrooms`
- `OneHotEncoder` on categorical column: `Neighborhood_Quality`

In [ ]:
#Question 4

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

num_features = ['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms']
cate_features = ['Neighborhood_Quality']

#building column transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), cate_features)
    ])

## Question 5 (20 Marks)

Build a complete **Pipeline** using Scikit-Learn that includes:
- The `ColumnTransformer`
- `SGDRegressor` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [ ]:
# Question 5

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import root_mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

# split
X = df.drop('House_Price', axis=1)
y = df['House_Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#categorize
num_features = ['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built', 'Lot_Size', 'Garage_Size']
cate_features = ['Neighborhood_Quality']

# create the ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), cate_features)
    ])

# create the Pipeline
model_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', SGDRegressor(random_state=42, max_iter=1000, tol=1e-3))
])

# train
model_pipeline.fit(X_train, y_train)

# predictions
y_pred = model_pipeline.predict(X_test)

# evaluate the model
rmse = rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"RMSE: {rmse:.2f}")
print(f"R-squared: {r2:.2f}")


# Print predicted vs actual values for the first 10 test samples
for i in range(10):
    print(f"Predicted: {y_pred[i]:,.2f}, Actual: {y_test.iloc[i]:,.2f}")

RMSE: 10258.77
R-squared: 1.00
Predicted: 869,913.14, Actual: 901,000.49
Predicted: 492,864.81, Actual: 494,537.51
Predicted: 943,647.13, Actual: 949,404.20
Predicted: 1,032,422.66, Actual: 1,040,389.05
Predicted: 776,037.11, Actual: 794,010.02
Predicted: 733,131.64, Actual: 724,033.56
Predicted: 992,108.75, Actual: 998,439.24
Predicted: 885,752.50, Actual: 909,713.44
Predicted: 796,034.87, Actual: 792,681.52
Predicted: 932,155.32, Actual: 947,490.78

---
## Question 6 (20 Marks)

Implement **Multiple Linear Regression** using **Scikit-Learn**:
- The `ColumnTransformer`
- `LinearRegression` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [ ]:
# Question 6
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error

# create the Pipeline
model_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

# train
model_pipeline.fit(X_train, y_train)

# make
y_pred = model_pipeline.predict(X_test)

# evaluate
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"RMSE: {rmse:.2f}")
print(f"R-squared: {r2:.2f}")


# Print predicted vs actual values for the first 10 test samples
for i in range(10):
    print(f"Predicted: {y_pred[i]:,.2f}, Actual: {y_test.iloc[i]:,.2f}")

RMSE: 10250.31
R-squared: 1.00
Predicted: 869,874.44, Actual: 901,000.49
Predicted: 493,008.02, Actual: 494,537.51
Predicted: 943,543.85, Actual: 949,404.20
Predicted: 1,032,332.24, Actual: 1,040,389.05
Predicted: 776,180.75, Actual: 794,010.02
Predicted: 733,011.80, Actual: 724,033.56
Predicted: 992,374.77, Actual: 998,439.24
Predicted: 885,753.69, Actual: 909,713.44
Predicted: 796,210.76, Actual: 792,681.52
Predicted: 932,031.03, Actual: 947,490.78

---
## Question 7 (10 Marks) (You have to explore the topic and use the equation via Numpy)
### Dont use LLMs , You can use Documentation

Implement **Multiple Linear Regression** using **only NumPy**:
- Pick random 100 datas from the dataset
- Use the Normal Equation: `θ = (XᵀX)⁻¹ Xᵀy`
- Use `Square_Footage`, `Num_Bedrooms`, and `Num_Bathrooms` as features
- Print the learned coefficients (θ values)

In [ ]:
# Question 7

# pick random 100 data points from the dataset
df = df.sample(n=100, random_state=42)

features = ['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms']
X = df[features].values
y = df['House_Price'].values

#using np
X_b = np.c_[np.ones(X.shape[0]), X]
theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y

# print the learned coefficients
print(f"Intercept: {theta[0]:.4f}")
print()
for i, feature in enumerate(features):
    print(f"{feature}: {theta[i+1]:.4f}")

Intercept: 20888.2595

Square_Footage: 202.3082
Num_Bedrooms: 8303.2810
Num_Bathrooms: 3020.3285